apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwc-config-pvc
spec:
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi