kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qwc-qgis-server-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem

