apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: qwc-api-gateway
  name: qwc-api-gateway
spec:
  ports:
    - name: "8088"
      port: 8088
      targetPort: 80
  selector:
    io.kompose.service: qwc-api-gateway
