apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: qwc-solr
  name: qwc-solr
spec:
  ports:
    - name: "8983"
      port: 8983
      targetPort: 8983
  selector:
    io.kompose.service: qwc-solr
