apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: qwc-postgis
  name: qwc-postgis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: qwc-postgis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: qwc-postgis
    spec:
      serviceAccountName: qwc-sa
      containers:
        - env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: qwc-postgis-secret
          image: sourcepole/qwc-base-db:16
          livenessProbe:
            exec:
              command:
                - pg_isready -U postgres
            periodSeconds: 10
          name: qwc-postgis
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: qwc-postgis-claim0
            - mountPath: /docker-entrypoint-initdb.d/2_setup-demo-data.sh
              name: qwc-postgis-cm1
              subPath: 2_setup-demo-data.sh
      restartPolicy: Always
      volumes:
        - name: qwc-postgis-claim0
          persistentVolumeClaim:
            claimName: qwc-postgis-claim0
        - configMap:
            items:
              - key: setup-demo-data.sh
                path: 2_setup-demo-data.sh
            name: qwc-postgis-cm1
          name: qwc-postgis-cm1

