apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: qwc-postgis-claim0
  name: qwc-postgis-claim0
spec:
  storageClassName: ocs-storagecluster-ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
