apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: qwc-document-service-claim2
  name: qwc-document-service-claim2
spec:
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
