apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: qwc-config-db-migrate
  name: qwc-config-db-migrate
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: sourcepole/qwc-base-db-migrate:latest-2025-lts
      name: latest-2025-lts
      referencePolicy:
        type: ""
