apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    io.kompose.service: qwc-data-service
  name: qwc-data-service
spec:
  replicas: 1
  selector:
    io.kompose.service: qwc-data-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: qwc-data-service
    spec:
      serviceAccountName: qwc-sa
      containers:
        - env:
            - name: ATTACHMENTS_BASE_DIR
              value: /attachments
            - name: JWT_COOKIE_CSRF_PROTECT
              value: "True"
            - name: JWT_COOKIE_SAMESITE
              value: Strict
            - name: JWT_SECRET_KEY
              value: my-secret-key
            - name: MAX_ATTACHMENT_FILE_SIZE
              value: "1048576"
            - name: SERVICE_GID
              value: "0"
            - name: SERVICE_MOUNTPOINT
              value: /api/v1/data
          image: ' '
          name: qwc-data-service
          volumeMounts:
            - mountPath: /srv/qwc_service/config
              name: qwc-data-service-cm0
              readOnly: true
            - mountPath: /attachments
              name: qwc-data-service-cm1
            - mountPath: /srv/pg_service.conf
              name: qwc-data-service-cm2
              readOnly: true
              subPath: pg_service.conf
      restartPolicy: Always
      volumes:
        - configMap:
            name: qwc-data-service-cm0
          name: qwc-data-service-cm0
        - configMap:
            name: qwc-data-service-cm1
          name: qwc-data-service-cm1
        - configMap:
            items:
              - key: pg_service.conf
                path: pg_service.conf
            name: qwc-data-service-cm2
          name: qwc-data-service-cm2
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - qwc-data-service
        from:
          kind: ImageStreamTag
          name: qwc-data-service:latest-2025-lts
      type: ImageChange
