apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwc-qgis-server-pvc
spec:
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi