apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: qwc-qgis-server
  name: qwc-qgis-server
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: qwc-qgis-server
