apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwc-map-viewer-assets-pvc
spec:
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi