apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    io.kompose.service: qwc-admin-gui
  name: qwc-admin-gui
spec:
  replicas: 1
  selector:
    io.kompose.service: qwc-admin-gui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: qwc-admin-gui
    spec:
      serviceAccountName: qwc-sa
      containers:
        - env:
            - name: DEFAULT_LOCALE
              value: en
            - name: GROUP_REGISTRATION_ENABLED
              value: "True"
            - name: JWT_COOKIE_CSRF_PROTECT
              value: "False"
            - name: JWT_COOKIE_SAMESITE
              value: Strict
            - name: JWT_SECRET_KEY
              value: my-secret-key
            - name: MAIL_DEFAULT_SENDER
              value: from@example.com
            - name: MAIL_SUPPRESS_SEND
              value: "True"
          image: ' '
          name: qwc-admin-gui
          volumeMounts:
            - mountPath: /srv/pg_service.conf
              name: qwc-admin-gui-cm0
              readOnly: true
              subPath: pg_service.conf
            - mountPath: /srv/qwc_service/config
              name: qwc-admin-gui-cm1
              readOnly: true
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: pg_service.conf
                path: pg_service.conf
            name: qwc-admin-gui-cm0
          name: qwc-admin-gui-cm0
        - configMap:
            name: qwc-admin-gui-cm1
          name: qwc-admin-gui-cm1
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - qwc-admin-gui
        from:
          kind: ImageStreamTag
          name: qwc-admin-gui:latest-2025-lts
      type: ImageChange
