apiVersion: v1
data:
  uwsgi.ini: |
    [uwsgi]
    socket = 0.0.0.0:9090
    uid = uwsgi
    gid = uwsgi
    emperor = /etc/uwsgi/conf.d
    emperor-tyrant = true
    cap = setgid,setuid
kind: ConfigMap
metadata:
  name: uwsgi-ini