apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: qwc
  namespace: qwc
  releaseName: qwc
  repo: https://camptocamp.github.io/helm-qwc-services/
  valuesFile: values.yaml
  version: 1.0.6

patches:
- path: remove-hostip-patch.yaml
