apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: qwc
  namespace: qwc
  releaseName: qwc
  repo: https://camptocamp.github.io/helm-qwc-services/
  valuesFile: values.yaml
  version: 1.0.6

patches:
  - qwc-admin-gui-remove-hostip-patch.yaml
  - qwc-auth-service-remove-hostip-patch.yaml
  - qwc-config-service-remove-hostip-patch.yaml
  - qwc-data-service-remove-hostip-patch.yaml
  - qwc-document-service-remove-hostip-patch.yaml
  - qwc-elevation-service-remove-hostip-patch.yaml
  - qwc-feature-info-service-remove-hostip-patch.yaml
  - qwc-fulltext-search-service-remove-hostip-patch.yaml
  - qwc-mapinfo-service-remove-hostip-patch.yaml
  - qwc-legend-service-remove-hostip-patch.yaml
  - qwc-print-service-remove-hostip-patch.yaml
  - qwc-map-viewer-remove-hostip-patch.yaml
  - qwc-ogc-service-remove-hostip-patch.yaml
  - qwc-permalink-service-remove-hostip-patch.yaml
