kind: Deployment
apiVersion: apps/v1
metadata:
  name: qwc-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      myLabel: qwc-nginx
  template:
    metadata:
      labels:
        myLabel: qwc-nginx
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-configuration
      containers:
        - name: qwc-nginx
          image: 'nginxinc/nginx-unprivileged:alpine3.22-perl'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/
    