apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwc-postgis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwc-postgis
  template:
    metadata:
      labels:
        app: qwc-postgis
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: qwc-postgis-secret
        image: sourcepole/qwc-base-db:16
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 10
          periodSeconds: 10
        name: qwc-postgis
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: db-data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: qwc-postgis-pvc
