apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwc-postgis-pvc
spec:
  storageClassName: ocs-storagecluster-ceph-rbd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi